version: 2.1

orbs:
  node: circleci/node@7.1.1
  aws-cli: circleci/aws-cli@5.4.1
  aws-s3: circleci/aws-s3@4.1.2

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - public/
  publish:
    executor: aws-s3/default
    steps:
      - aws-cli/setup:
          profile_name: default
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/copy:
          from: public/
          to: $S3_BUCKET_TA
          arguments: --recursive

workflows:
  build-publish-s3:
    jobs:
      - build
      - publish:
          requires:
            - build
