version: 2.1

orbs:
  node: circleci/node@7.1.1
  aws-s3: circleci/aws-s3@4.1.2

workflows:
  build-publish-s3:
    jobs:
      - node/run:
          npm-run: build
          post-steps:
            - aws-s3/copy:
                from: public/
                to: $S3_BUCKET_TA
                arguments: --recursive
